[package]
name = "pitufo"
version = "1.0.0"
authors = ["ian-hamlin <ian@ihamlin.co.uk>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
walkdir = "2"
serde = "1.0.91"
serde_json = "1.0"
argh = "0.1.3"